name = "Images"
uuid = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
version = "0.25.2"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Graphics = "a2bd30eb-e257-5431-a919-1863eab51364"
ImageAxes = "2803e5a7-5153-5ecf-9a86-9b4c37f5f5ac"
ImageBase = "c817782e-172a-44cc-b673-b171935fbb9e"
ImageContrastAdjustment = "f332f351-ec65-5f6a-b3d1-319c6670881a"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageDistances = "51556ac3-7006-55f5-8cb3-34580c88182d"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
ImageMetadata = "bc367c6b-8a6b-528e-b4bd-a4b897500b49"
ImageMorphology = "787d08f9-d448-5407-9aad-5290dd7ab264"
ImageQualityIndexes = "2996bd0c-7a13-11e9-2da2-2f5ce47296a9"
ImageSegmentation = "80713f31-8817-5129-9cf8-209ff8fb23e1"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
IndirectArrays = "9b13fd28-a010-5f03-acff-a1bbcff69959"
IntegralArrays = "1d092043-8f09-5a30-832f-7509e371ab51"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TiledIteration = "06e1c1a7-607b-532d-9fad-de7d9aa2abac"

[compat]
FileIO = "1"
Graphics = "0.4, 1.0"
ImageAxes = "0.6.9"
ImageBase = "0.1.5"
ImageContrastAdjustment = "0.3.3"
ImageCore = "0.9.3"
ImageDistances = "0.2.5"
ImageFiltering = "0.7.1"
ImageIO = "0.3, 0.4, 0.5, 0.6"
ImageMagick = "1"
ImageMetadata = "0.9.7"
ImageMorphology = "0.3, 0.4"
ImageQualityIndexes = "0.3"
ImageSegmentation = "1.7"
ImageShow = "0.3"
ImageTransformations = "0.9"
IndirectArrays = "0.5, 1"
IntegralArrays = "0.1"
Reexport = "1.1"
StaticArrays = "0.8, 0.9, 0.10, 0.11, 0.12, 1.0"
StatsBase = "0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32, 0.33"
Suppressor = "0.2"
TiledIteration = "0.2, 0.3"
julia = "1.3"

[extras]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[targets]
test = ["FFTW", "LinearAlgebra", "Random", "Suppressor", "Test", "TestImages"]
